-- Dados da planilha Apoio 2026 (sem a aba Oficina Conecte).
-- Rode no SQL Editor DEPOIS de supabase/sql/rodar-no-editor.sql
-- Substitui estoque, cardápio, preços e programações de exemplo.
-- Não apaga members nem user_roles (o admin já está vinculado).

DELETE FROM public.event_inventory;
DELETE FROM public.event_assignments;
DELETE FROM public.event_tasks;
DELETE FROM public.finance_entries;
DELETE FROM public.events;
DELETE FROM public.menu_ingredients;
DELETE FROM public.ingredient_prices;
DELETE FROM public.menus;
DELETE FROM public.inventory_items;

-- Inventário
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pincéis', 13, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Varais de Luzes com lâmpadas', 5, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolos de Pintura', 7, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Fita Led', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Suporte para Tinta', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Canudos de luz', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Preta', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Holofotes', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Vermelha', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Flamingo', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Amarela', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Coqueiro', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Laranja', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Pisca de Pilha Colorido', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Azul', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Pisca de Tomada Colorido', 4, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Guache Verde', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Pisca de Tomada Branco', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Suvinil Amarelo', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Iluminação', 'Quadro Recepção', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Suvinil Azul', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Festões de Natal', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tinta Suvinil Laranja', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Velas de Mesa', 20, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas de Setin Branca', 4, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Flores Variadas', NULL, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas de Setin Amarela', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Vasos com flores', 11, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas de Setin Vermelha', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Potes de mesa', 11, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas de Setin Laranja', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Vasos e plantas', 'Pinhas', NULL, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas de Setin Azul', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Barraca de Campo', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fita Zebrada', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Bomba de Ar', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fita Zebrada com Cola', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Cones Baixos', 6, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fita "Life is Good"', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Buzinas', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas Azuis', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Apitos', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas Vermelhas', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Raquetes Tênis de Mesa', 6, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas Rosa', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Suportes Para Rede de Tênis de Mesa', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas Amarela', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Redes de Tênis de Mesa', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Fitas Branca', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Lanternas', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolos de Fita Dupla Face', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Escada de Chão', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolos de Fita Crepe', 5, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Artigos de esporte', 'Faixa de Capitao', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Fita Durex', 10, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Fantasias', 'Potes de Sangue Falso', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Cordão Palha', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Fantasias', 'Óculos 3D', 10, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Corda', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Fantasias', 'Chápeu de Palha', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Barbante Branco', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Fantasias', 'Chápeu de Caubói', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Linha Amarela', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Fantasias', 'Colares Havaianos', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Linha Laranja', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Bandeira Conecte', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Linha Branca', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Roleta de sorteio', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolo de Nilon', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Lousa de giz pequena', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Prata', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Letras "conecte"', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Roxo', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Teia falsa', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Azul Escuro', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Correias de segurança', NULL, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Azul Claro', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Relógio despertador', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Cobre', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Campainha de atendimento', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Gliter Dourado', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Cofre com moedas de ouro', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Kit de Gliters Variados', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Decoração ambiente', 'Bolinhas de gude', NULL, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Bexiga amarela', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Bexiga Verde', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Bexiga Azul', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Bexiga Branca', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Enchedores de Bexiga', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Varetas para Bexiga', NULL, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Cola Branca', 5, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pistolas de Cola Quente', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tubos de Cola Quente Grande', 10, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tubos de Cola Quente Pequena', 5, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Prancheta', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Giz Branco', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Grampeador Grande', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Grampeador Pequeno', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Grampos Grandes', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Grampos Pequenos', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Bloco de Notas', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Giz de Cera', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Giz Pastel', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Lápis de Cor', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote de Alfinetes', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Estiletes', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Estojo com material de Escrita Diverso', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tesouras', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Tesoura Zig-Zag', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Canetas Quardro Branco Cores Variadas', 5, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolos de Papel Crempo (Rosa,Roxo,Branco,Amarelo,Verde)', NULL, 'diversos');
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Folhas de EVA Amarelo', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Folha de EVA Vermelho', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Folha de EVA Branco', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Folha de EVA Preto', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacotes de Etiquetas', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Papel seda Branco e Preto', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Pacote Papel Holgráfico de Cores Variadas', 1, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Folhas Papel Crafit Grande', 14, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Rolos de Papel Alumínio', 2, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Toalhas de Palha', 3, NULL);
INSERT INTO public.inventory_items (sector, name, quantity, quantity_note) VALUES ('Papelaria', 'Papéis de Embrulho diversos', 2, NULL);

-- Tabela de preços (aba precificação, colunas A-E)
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Copos descartáveis', 100, 'und', 4.2, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Copos térmicos descartáveis', 20, 'und', 7.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pratos descartáveis', 10, 'und', 2.09, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Garfos descartáveis', 50, 'und', 9.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Facas descartáveis', 50, 'und', 9.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Colher plástica descartável', 50, 'und', 9.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pão de forma', 15, 'Fatias', 8.49, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pão caseiro', 9, 'und', 27, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pão para cachorro quente', 6, 'und', 6.98, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pão para hamburguer', 6, 'und', 4.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Acém moído', 1000, 'g', 43.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Peito de frango', 1000, 'g', 21.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Calabresa', 1000, 'g', 26.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Carne de hamburguer', 1, 'und', 4.8, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Salsicha', 50, 'und', 28.8, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Presunto', 1000, 'g', 34, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Queijo mussarela', 62, 'Fatias', 67, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Queijo parmesão ralado', 1000, 'g', 89.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Arroz branco', 1000, 'g', 4.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Batata', 1000, 'g', 4.98, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Macarrão parafuso', 500, 'g', 3.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Milho para pipoca', 500, 'g', 4.6, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Batata palha', 105, 'g', 9.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Bolo', 20, 'Fatias', 25, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Leite em pó', 400, 'g', 15.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Leite condensado', 395, 'ml', 5.6, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Chocolate em pó', 200, 'g', 15.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Creme  de leite', 200, 'ml', 2.69, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Amido de milho', 200, 'g', 6.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Maionese', 657, 'ml', 14.49, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Mostarda', 255, 'ml', 15.69, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Ketchup', 567, 'ml', 15.49, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Molho de tomate', 300, 'ml', 3.19, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Molho branco', 240, 'ml', 11.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Óleo de milho', 900, 'ml', 7.19, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Alho', 1000, 'g', 15, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Cebola', 1000, 'g', 5.29, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Tempero Sazon pipoca', 12, 'Sachês', 5.5, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Alface', 20, 'Folhas', 8, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Tomate', 80, 'Fatias', 15, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Laranja pêra', 1000, 'g', 8, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Suco de uva', 900, 'ml', 19.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Suco de laranja', 900, 'ml', 19.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Chá gelado', 2000, 'ml', 14.99, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Café solúvel extraforte', 500, 'g', 35.9, NULL) ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Pizza', 20, 'fatias', 81, 'Pizza Mais') ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Salgadinhos', 100, 'und', 45, '19 98196-1051') ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Esfiha', 1, 'und', 2.6, 'Art Massas') ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Picolé', 1, 'und', 2.5, 'Sergel (a partir de 20 un)') ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;
INSERT INTO public.ingredient_prices (name, pack_quantity, unit, price, where_to_buy) VALUES ('Sorvete de massa', 2000, 'ml', 35, 'Sergel') ON CONFLICT (name) DO UPDATE SET pack_quantity = EXCLUDED.pack_quantity, unit = EXCLUDED.unit, price = EXCLUDED.price;


-- Cardápio e receitas
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Bebidas', 'Copos e bebidas do Conecte.', 1.48, NULL);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Copos descartáveis', '1,5 und', 'ingrediente', 'Atacadão', NULL, 1 FROM public.menus WHERE name = 'Bebidas';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebida', '200ml', 'ingrediente', 'Atacadão, Dalben', 'Distribuição: Coca zero 0,55 · Coca 0,15 · Sprite 0,15 · sucos 0,15', 2 FROM public.menus WHERE name = 'Bebidas';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Strogonoff de frango', 'Strogonoff com arroz, batata palha e bebidas.', 20, 25);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Batata palha', '30g', 'ingrediente', 'Atacadão ou Dalben', NULL, 1 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Arroz', '220g (81,5g cru)', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Peito de frango', '250g (320g cru)', 'ingrediente', 'Açougue do Concon ou Swift', 'Pegar já moído para strogonoff', 3 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Molho', '70g', 'ingrediente', 'Fazer (Atacadão ou Dalben)', '20g de ketchup + 40g de creme de leite', 4 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Cebola', '10g', 'ingrediente', 'Atacadão ou Dalben', 'Para refogar com o frango', 5 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Alho', '8g (1 dente médio)', 'ingrediente', NULL, 'Para temperar o arroz', 6 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Azeite e sal', 'Suficiente', 'ingrediente', 'Armário da tenda', 'Temos guardado no armário da tenda', 7 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', 'Atacadão ou Dalben', NULL, 8 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Prato descartável', '1 und', 'ingrediente', NULL, NULL, 9 FROM public.menus WHERE name = 'Strogonoff de frango';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Lanche natural', 'Lanche natural + suco. Servir cortado ao meio.', 15, 15);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Lanche natural', '3 metades', 'ingrediente', 'Atacadão ou Dalben', 'Servir cortados ao meio', 1 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Queijo mussarela', '1 fatia / und', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Alface', '1 folha / und', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Tomate', '1 rodela / und', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Pão caseirinho', '1 und', 'ingrediente', NULL, NULL, 5 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Maionese', '8g / und', 'ingrediente', NULL, NULL, 6 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Suco de laranja natural', '310ml', 'ingrediente', NULL, NULL, 7 FROM public.menus WHERE name = 'Lanche natural';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Coffee break', 'Bebidas, café, bolo e lanche.', 8, 15);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '200ml', 'ingrediente', 'Atacadão ou Dalben', 'Uva 0,4 · laranja 0,35 · chá gelado 0,1 · água saborizada 0,15', 1 FROM public.menus WHERE name = 'Coffee break';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Café', '50ml', 'ingrediente', NULL, 'Levar chaleira elétrica para fazer na hora', 2 FROM public.menus WHERE name = 'Coffee break';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bolo', '1 fatia', 'ingrediente', 'Casa de bolos', 'Cenoura 0,6 · chocolate 0,4', 3 FROM public.menus WHERE name = 'Coffee break';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Lanche', '1 und', 'ingrediente', 'Atacadão ou Dalben', 'Metades: pão de forma, presunto e queijo', 4 FROM public.menus WHERE name = 'Coffee break';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Chocolate quente', 'Chocolate quente para noite de jogos / pipoca.', NULL, NULL);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Água', '200ml', 'ingrediente', 'Atacadão ou Dalben', NULL, 1 FROM public.menus WHERE name = 'Chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Leite em pó', '40g', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Chocolate em pó 50%', '30g', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Leite condensado', '20g', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Amido de milho', '10g', 'ingrediente', NULL, NULL, 5 FROM public.menus WHERE name = 'Chocolate quente';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Cachorro quente', 'Cachorro quente + bebidas. Cada um monta o seu.', 15, 20);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Cachorro quente', '2 und', 'ingrediente', 'Atacadão ou Dalben', 'Cada um monta o seu', 1 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Pão para cachorro quente', '1 und / un', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Salsicha', '1 und / un', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Purê de batata', '90g (60,2g cru)', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Ketchup', '15g / un', 'ingrediente', NULL, NULL, 5 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Mostarda', '15g / un', 'ingrediente', NULL, NULL, 6 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Batata palha', '15g / un', 'ingrediente', NULL, NULL, 7 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 8 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Prato descartável', '1 und', 'ingrediente', NULL, NULL, 9 FROM public.menus WHERE name = 'Cachorro quente';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Pizza', 'Pizza + bebidas. Pizza Mais (19) 3289-0320 ou Nonna Braçuda (19) 99585-7744. No Pizza Mais demora até 1h10.', 25, 25);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Pizza', '3 pedaços', 'ingrediente', 'Pizza Mais ou Nonna Braçuda', 'No Pizza Mais demora até 1h10. Frango c/ catupiry 0,3 · lombinho 0,2 · marguerita 0,2', 1 FROM public.menus WHERE name = 'Pizza';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Pizza';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Macarronada', 'Macarronada + bebidas. Cada um monta o seu.', 15, 25);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Macarrão', '450g (184g cru)', 'ingrediente', 'Atacadão ou Dalben', 'Cada um monta o seu', 1 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Molho de tomate', '70g', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Molho branco', '70g', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Carne moída', '50g', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Calabresa', '30g', 'ingrediente', NULL, NULL, 5 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Queijo parmesão ralado', '15g', 'ingrediente', NULL, NULL, 6 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Alho', '8g (1 dente médio)', 'ingrediente', NULL, NULL, 7 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Azeite e sal', '-', 'ingrediente', 'Armário da tenda', 'Temos guardado no armário da tenda', 8 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 9 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Prato descartável', '1 und', 'ingrediente', NULL, NULL, 10 FROM public.menus WHERE name = 'Macarronada';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Hambúrguer', 'Hambúrguer + bebidas. Carne no Açougue dos Concons.', 15, 25);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Hambúrguer', '1 und', 'ingrediente', 'Açougue dos Concons (carne); Atacadão ou Dalben (restante)', NULL, 1 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Carne', '1 und / un', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Queijo mussarela', '2 fatias / un', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Alface', '2 folhas / un', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Tomate', '3 rodelas / un', 'ingrediente', NULL, 'Um tomate médio rende cerca de 10 rodelas', 5 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Cebola', '1/3 rodela / un', 'ingrediente', NULL, 'Uma cebola média rende cerca de 12 rodelas', 6 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Pão', '1 und / un', 'ingrediente', NULL, NULL, 7 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Ketchup', '15g / un', 'ingrediente', NULL, NULL, 8 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Maionese', '15g / un', 'ingrediente', NULL, NULL, 9 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 10 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Prato descartável', '1 und', 'ingrediente', NULL, NULL, 11 FROM public.menus WHERE name = 'Hambúrguer';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Salgadinhos de festa', 'Salgados + bebidas. Tel. 19 98196-1051. Não emitem nota fiscal — pagar com o dinheiro físico do Conecte.', 15, 20);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Salgadinhos', '20 und', 'ingrediente', '19 98196-1051', 'Não emitem nota fiscal. Distribuição: risole carne 0,3 · risole presunto/queijo 0,3 · coxinha 0,2 · bolinha de queijo 0,2', 1 FROM public.menus WHERE name = 'Salgadinhos de festa';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Salgadinhos de festa';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Prato descartável', '1 und', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Salgadinhos de festa';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Esfihas', 'Esfiha fechada + bebida. Art Massas (19) 3289-1185 — encomendar com antecedência.', 20, 20);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Esfiha', '5 und', 'ingrediente', 'Art Massas - (19) 3289-1185', 'Encomendar com antecedência. Carne 0,4 · calabresa 0,2 · frango 0,4', 1 FROM public.menus WHERE name = 'Esfihas';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Bebidas', '250ml', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Esfihas';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Pipoca + chocolate quente', 'Pipoca salgada com chocolate quente.', 10, 15);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Milho para pipoca', '50g', 'ingrediente', 'Atacadão ou Dalben', NULL, 1 FROM public.menus WHERE name = 'Pipoca + chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Óleo', '25ml', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Pipoca + chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Sazon pipoca', '0,5 sachê', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Pipoca + chocolate quente';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Chocolate quente', '1 porção', 'ingrediente', NULL, 'Ver receita de chocolate quente', 4 FROM public.menus WHERE name = 'Pipoca + chocolate quente';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Picolé', 'Dois picolés + suco. Sergel — Caio Bueno consegue preço privilegiado. Até 20 un R$3,50; a partir de 20 un R$2,50.', 10, 15);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Picolé', '2 und', 'ingrediente', 'Sergel', 'Chocolate 0,3 · leite ninho 0,3 · flocos 0,15 · morango 0,15 · limão 0,1', 1 FROM public.menus WHERE name = 'Picolé';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Suco', '310ml', 'ingrediente', NULL, NULL, 2 FROM public.menus WHERE name = 'Picolé';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Sorvete de massa', 'Sorvete de massa. Sergel — Caio Bueno consegue preço privilegiado.', 10, 15);
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Sorvete de massa', '330ml', 'ingrediente', 'Sergel', 'Chocolate 0,4 · leite ninho 0,4 · flocos 0,2', 1 FROM public.menus WHERE name = 'Sorvete de massa';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Casquinha de sorvete', '1 und', 'ingrediente', 'Atacadão', NULL, 2 FROM public.menus WHERE name = 'Sorvete de massa';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Pote térmico descartável', '1 und', 'ingrediente', NULL, NULL, 3 FROM public.menus WHERE name = 'Sorvete de massa';
INSERT INTO public.menu_ingredients (menu_id, name, qty_per_person, kind, where_to_buy, notes, sort_order) SELECT id, 'Colher plástica descartável', '1 und', 'ingrediente', NULL, NULL, 4 FROM public.menus WHERE name = 'Sorvete de massa';
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Churrasco', 'Churrasco dos homens — sem ficha de receita na planilha.', NULL, NULL);
INSERT INTO public.menus (name, description, min_price_per_person, charged_price_per_person) VALUES ('Lanche comunitário', 'Festa de encerramento — cardápio a confirmar.', NULL, NULL);

-- Programações (escala 2º semestre 2026)
-- 1º semestre na planilha está só com o gabarito, sem eventos preenchidos.
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Start Impulse + Conecte', '2026-08-01'::date, '18:00', 'EJ / Sala 8 / Quadra / Tenda', 'Hambúrguer', (SELECT id FROM public.menus WHERE name = 'Hambúrguer'), NULL, NULL, 'realizada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Beatriz' WHERE e.title = 'Start Impulse + Conecte' AND e.event_date = '2026-08-01'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Noite de jogos', '2026-08-08'::date, '19:00', 'Sala 7 e 8 e quadra', 'Salgadinhos de festa', (SELECT id FROM public.menus WHERE name = 'Salgadinhos de festa'), 'Fornecedor não emite NF — pagar com dinheiro físico do Conecte.', '19 98196-1051', 'realizada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael B' WHERE e.title = 'Noite de jogos' AND e.event_date = '2026-08-08'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Beatriz' WHERE e.title = 'Noite de jogos' AND e.event_date = '2026-08-08'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Informal', '2026-08-15'::date, NULL, NULL, NULL, NULL, NULL, NULL, 'realizada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Churrasco dos homens (conferência das mulheres)', '2026-08-22'::date, '12:00', 'Casa do Dinnout?', 'Churrasco', (SELECT id FROM public.menus WHERE name = 'Churrasco'), NULL, NULL, 'planejada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-08-29'::date, NULL, NULL, 'Cachorro quente', (SELECT id FROM public.menus WHERE name = 'Cachorro quente'), NULL, NULL, 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Nicholas' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-08-29'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Carla' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-08-29'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Acampa Conecte', '2026-09-05'::date, NULL, NULL, NULL, NULL, NULL, NULL, 'planejada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Informal', '2026-09-12'::date, NULL, NULL, NULL, NULL, NULL, NULL, 'planejada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-09-19'::date, '19:00', 'EJ', 'Pizza', (SELECT id FROM public.menus WHERE name = 'Pizza'), 'Pizza Mais demora até 1h10.', '(19) 3289-0320 / Nonna Braçuda (19) 99585-7744', 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Isabela S' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-09-19'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-09-19'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Planejamento', '2026-09-26'::date, '19:00', 'Sala 7', 'Esfihas', (SELECT id FROM public.menus WHERE name = 'Esfihas'), 'Na planilha: Esfihas (picolé?). Encomendar esfiha com antecedência.', '(19) 3289-1185', 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Beatriz' WHERE e.title = 'Planejamento' AND e.event_date = '2026-09-26'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Isabela L' WHERE e.title = 'Planejamento' AND e.event_date = '2026-09-26'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-10-03'::date, '19:00', 'EJ', 'Hambúrguer', (SELECT id FROM public.menus WHERE name = 'Hambúrguer'), NULL, NULL, 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Beatriz' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-10-03'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael B' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-10-03'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Informal', '2026-10-10'::date, NULL, NULL, NULL, NULL, NULL, NULL, 'planejada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-10-17'::date, '19:00', 'EJ', 'Cachorro quente', (SELECT id FROM public.menus WHERE name = 'Cachorro quente'), NULL, NULL, 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Nicholas' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-10-17'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Carla' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-10-17'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Noite de jogos', '2026-10-24'::date, NULL, NULL, 'Salgadinhos de festa', (SELECT id FROM public.menus WHERE name = 'Salgadinhos de festa'), 'Fornecedor não emite NF — pagar com dinheiro físico do Conecte.', '19 98196-1051', 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael' WHERE e.title = 'Noite de jogos' AND e.event_date = '2026-10-24'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Isabela S' WHERE e.title = 'Noite de jogos' AND e.event_date = '2026-10-24'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Semana da solidariedade', '2026-10-31'::date, NULL, NULL, NULL, NULL, NULL, NULL, 'planejada');
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-11-07'::date, NULL, NULL, 'Pizza', (SELECT id FROM public.menus WHERE name = 'Pizza'), 'Pizza Mais demora até 1h10.', '(19) 3289-0320 / Nonna Braçuda (19) 99585-7744', 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Isabela L' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-11-07'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael B' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-11-07'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('DayCamp com Impulse', '2026-11-14'::date, NULL, NULL, 'Eles que mandam', NULL, 'Alimentação fica a cargo do Impulse.', NULL, 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Beatriz' WHERE e.title = 'DayCamp com Impulse' AND e.event_date = '2026-11-14'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael B' WHERE e.title = 'DayCamp com Impulse' AND e.event_date = '2026-11-14'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Culto Conecte', '2026-11-21'::date, '19:00', 'EJ', 'Esfihas', (SELECT id FROM public.menus WHERE name = 'Esfihas'), 'Encomendar na Art Massas com antecedência.', '(19) 3289-1185', 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Nicholas' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-11-21'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Carla' WHERE e.title = 'Culto Conecte' AND e.event_date = '2026-11-21'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.events (title, event_date, event_time, location, food_label, menu_id, notes, phones, status) VALUES ('Festa de encerramento', '2026-11-28'::date, NULL, NULL, 'Lanche comunitário?', (SELECT id FROM public.menus WHERE name = 'Lanche comunitário'), 'Cardápio a confirmar na planilha.', NULL, 'planejada');
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'decoração' FROM public.events e JOIN public.members m ON m.full_name = 'Isabela S' WHERE e.title = 'Festa de encerramento' AND e.event_date = '2026-11-28'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;
INSERT INTO public.event_assignments (event_id, member_id, area) SELECT e.id, m.id, 'alimentação' FROM public.events e JOIN public.members m ON m.full_name = 'Rafael' WHERE e.title = 'Festa de encerramento' AND e.event_date = '2026-11-28'::date ON CONFLICT (event_id, member_id, area) DO NOTHING;

INSERT INTO public.event_tasks (event_id, title, sort_order)
SELECT e.id, t.title, t.sort_order FROM public.events e
CROSS JOIN (VALUES
  ('Levantar quantidade de pessoas', 1),
  ('Comprar ingredientes', 2),
  ('Preparar o alimento', 3),
  ('Decorar o local', 4),
  ('Servir', 5),
  ('Limpar e guardar', 6),
  ('Guardar nota fiscal e pedir reembolso', 7)
) AS t(title, sort_order);

-- Caixa Conecte na planilha está zerado (sem gastos/receitas lançados).
