/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAlmoxarifadoRouteImport } from './routes/_authenticated/almoxarifado'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedCardapioIndexRouteImport } from './routes/_authenticated/cardapio/index'
import { Route as AuthenticatedCardapioIdRouteImport } from './routes/_authenticated/cardapio/$id'
import { Route as AuthenticatedCardapioNovaRouteImport } from './routes/_authenticated/cardapio/nova'
import { Route as AuthenticatedCardapioPrecosRouteImport } from './routes/_authenticated/cardapio/precos'
import { Route as AuthenticatedProgramacoesIndexRouteImport } from './routes/_authenticated/programacoes/index'
import { Route as AuthenticatedProgramacoesIdRouteImport } from './routes/_authenticated/programacoes/$id'
import { Route as AuthenticatedProgramacoesNovaRouteImport } from './routes/_authenticated/programacoes/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlmoxarifadoRoute =
  AuthenticatedAlmoxarifadoRouteImport.update({
    id: '/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardapioIndexRoute =
  AuthenticatedCardapioIndexRouteImport.update({
    id: '/cardapio/',
    path: '/cardapio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardapioIdRoute = AuthenticatedCardapioIdRouteImport.update({
  id: '/cardapio/$id',
  path: '/cardapio/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardapioNovaRoute =
  AuthenticatedCardapioNovaRouteImport.update({
    id: '/cardapio/nova',
    path: '/cardapio/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardapioPrecosRoute =
  AuthenticatedCardapioPrecosRouteImport.update({
    id: '/cardapio/precos',
    path: '/cardapio/precos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramacoesIndexRoute =
  AuthenticatedProgramacoesIndexRouteImport.update({
    id: '/programacoes/',
    path: '/programacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramacoesIdRoute =
  AuthenticatedProgramacoesIdRouteImport.update({
    id: '/programacoes/$id',
    path: '/programacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramacoesNovaRoute =
  AuthenticatedProgramacoesNovaRouteImport.update({
    id: '/programacoes/nova',
    path: '/programacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/cardapio/$id': typeof AuthenticatedCardapioIdRoute
  '/cardapio/nova': typeof AuthenticatedCardapioNovaRoute
  '/cardapio/precos': typeof AuthenticatedCardapioPrecosRoute
  '/programacoes/$id': typeof AuthenticatedProgramacoesIdRoute
  '/programacoes/nova': typeof AuthenticatedProgramacoesNovaRoute
  '/cardapio/': typeof AuthenticatedCardapioIndexRoute
  '/programacoes/': typeof AuthenticatedProgramacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/cardapio/$id': typeof AuthenticatedCardapioIdRoute
  '/cardapio/nova': typeof AuthenticatedCardapioNovaRoute
  '/cardapio/precos': typeof AuthenticatedCardapioPrecosRoute
  '/programacoes/$id': typeof AuthenticatedProgramacoesIdRoute
  '/programacoes/nova': typeof AuthenticatedProgramacoesNovaRoute
  '/cardapio': typeof AuthenticatedCardapioIndexRoute
  '/programacoes': typeof AuthenticatedProgramacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/cardapio/$id': typeof AuthenticatedCardapioIdRoute
  '/_authenticated/cardapio/nova': typeof AuthenticatedCardapioNovaRoute
  '/_authenticated/cardapio/precos': typeof AuthenticatedCardapioPrecosRoute
  '/_authenticated/programacoes/$id': typeof AuthenticatedProgramacoesIdRoute
  '/_authenticated/programacoes/nova': typeof AuthenticatedProgramacoesNovaRoute
  '/_authenticated/cardapio/': typeof AuthenticatedCardapioIndexRoute
  '/_authenticated/programacoes/': typeof AuthenticatedProgramacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/almoxarifado'
    | '/calendario'
    | '/equipe'
    | '/financeiro'
    | '/inicio'
    | '/cardapio/$id'
    | '/cardapio/nova'
    | '/cardapio/precos'
    | '/programacoes/$id'
    | '/programacoes/nova'
    | '/cardapio/'
    | '/programacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/almoxarifado'
    | '/calendario'
    | '/equipe'
    | '/financeiro'
    | '/inicio'
    | '/cardapio/$id'
    | '/cardapio/nova'
    | '/cardapio/precos'
    | '/programacoes/$id'
    | '/programacoes/nova'
    | '/cardapio'
    | '/programacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/almoxarifado'
    | '/_authenticated/calendario'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/inicio'
    | '/_authenticated/cardapio/$id'
    | '/_authenticated/cardapio/nova'
    | '/_authenticated/cardapio/precos'
    | '/_authenticated/programacoes/$id'
    | '/_authenticated/programacoes/nova'
    | '/_authenticated/cardapio/'
    | '/_authenticated/programacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/almoxarifado': {
      id: '/_authenticated/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAlmoxarifadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapio/': {
      id: '/_authenticated/cardapio/'
      path: '/cardapio'
      fullPath: '/cardapio/'
      preLoaderRoute: typeof AuthenticatedCardapioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapio/$id': {
      id: '/_authenticated/cardapio/$id'
      path: '/cardapio/$id'
      fullPath: '/cardapio/$id'
      preLoaderRoute: typeof AuthenticatedCardapioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapio/nova': {
      id: '/_authenticated/cardapio/nova'
      path: '/cardapio/nova'
      fullPath: '/cardapio/nova'
      preLoaderRoute: typeof AuthenticatedCardapioNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapio/precos': {
      id: '/_authenticated/cardapio/precos'
      path: '/cardapio/precos'
      fullPath: '/cardapio/precos'
      preLoaderRoute: typeof AuthenticatedCardapioPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacoes/': {
      id: '/_authenticated/programacoes/'
      path: '/programacoes'
      fullPath: '/programacoes/'
      preLoaderRoute: typeof AuthenticatedProgramacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacoes/$id': {
      id: '/_authenticated/programacoes/$id'
      path: '/programacoes/$id'
      fullPath: '/programacoes/$id'
      preLoaderRoute: typeof AuthenticatedProgramacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacoes/nova': {
      id: '/_authenticated/programacoes/nova'
      path: '/programacoes/nova'
      fullPath: '/programacoes/nova'
      preLoaderRoute: typeof AuthenticatedProgramacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlmoxarifadoRoute: typeof AuthenticatedAlmoxarifadoRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedCardapioIdRoute: typeof AuthenticatedCardapioIdRoute
  AuthenticatedCardapioNovaRoute: typeof AuthenticatedCardapioNovaRoute
  AuthenticatedCardapioPrecosRoute: typeof AuthenticatedCardapioPrecosRoute
  AuthenticatedProgramacoesIdRoute: typeof AuthenticatedProgramacoesIdRoute
  AuthenticatedProgramacoesNovaRoute: typeof AuthenticatedProgramacoesNovaRoute
  AuthenticatedCardapioIndexRoute: typeof AuthenticatedCardapioIndexRoute
  AuthenticatedProgramacoesIndexRoute: typeof AuthenticatedProgramacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlmoxarifadoRoute: AuthenticatedAlmoxarifadoRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedCardapioIdRoute: AuthenticatedCardapioIdRoute,
  AuthenticatedCardapioNovaRoute: AuthenticatedCardapioNovaRoute,
  AuthenticatedCardapioPrecosRoute: AuthenticatedCardapioPrecosRoute,
  AuthenticatedProgramacoesIdRoute: AuthenticatedProgramacoesIdRoute,
  AuthenticatedProgramacoesNovaRoute: AuthenticatedProgramacoesNovaRoute,
  AuthenticatedCardapioIndexRoute: AuthenticatedCardapioIndexRoute,
  AuthenticatedProgramacoesIndexRoute: AuthenticatedProgramacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
